### ISSUE TITLE
'cuwire boards' command fails..

### ISSUE THREAD

**Issue by kaalabs** [apla/cuwire#2]
I've checked, hardware folder exists and board selections functions fine in the Arduino 1.5.8 IDE. Uses standard Arduino IDE folder locations.

this is the output:

MacBook-van-Remco:tools remcokortekaas$ cuwire boards

node.js:838
    var cwd = process.cwd();
                      ^
Error: ENOENT, no such file or directory
    at Function.startup.resolveArgv0 (node.js:838:23)
    at startup (node.js:58:13)
    at node.js:929:3

**Comment by kaalabs** [comment]
Closing / opening terminal window (on Mac OS X). Gave it another try, this time with different outcome / error:

MacBook-van-Remco:~ remcokortekaas$ cuwire boards
bad config for: recipe.size.regex.data ^(?:.data|.bss|.noinit)\s+([0-9]+).*
bad config for: recipe.size.regex.eeprom ^(?:.eeprom)\s+([0-9]+).*
cuwire using runtime from /Applications/Arduino.app/Contents/Java
cuwire boards available:

TypeError: Cannot read property 'version' of undefined
    at /usr/local/lib/node_modules/cuwire/cli.js:313:53
    at Array.forEach (native)
    at ArduinoCli.showBoards (/usr/local/lib/node_modules/cuwire/cli.js:312:33)
    at null.<anonymous> (/usr/local/lib/node_modules/cuwire/cli.js:211:20)
    at ArduinoCli.launchCommand (/usr/local/lib/node_modules/cuwire/cli.js:214:2)
    at null.<anonymous> (/usr/local/lib/node_modules/cuwire/cli.js:192:8)
    at emit (events.js:92:17)
    at null.<anonymous> (/usr/local/lib/node_modules/cuwire/data.js:132:8)
    at emit (events.js:117:20)
    at null._onTimeout (/usr/local/lib/node_modules/cuwire/data.js:171:11)

**Comment by apla** [comment]
second error I can understand. first one seems like nodejs internal error, cuwire doesn't contain file named `node.js`

**Comment by apla** [comment]
fixed obvious thing, please try:
1. copy cli.js from https://gist.github.com/apla/78781f0032f5a5cea272
2. run node ./cli.js boards

**Comment by kaalabs** [comment]
Wow, fast response! Thank you. This the resulting error:

node cli.js boards

module.js:340
    throw err;
          ^
Error: Cannot find module 'cuwire/data'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/remcokortekaas/Documents/Arduino/hardware/cli.js:2:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by apla** [comment]
try 
NODE_PATH=/usr/local/lib/node_modules node cli.js boards

**Comment by kaalabs** [comment]
Hi. Tried and failed still same error not being able to find cuwire/data module

Verified path setting by: echo $NODE_PATH    it is correct

**Comment by apla** [comment]
hmmm, works fine for me, just tested it. ok, try another way:
1. install newest cuwire by `npm install -g apla/cuwire`
2. run as usual `cuwire boards`

and, please, tell me what version of node you using.

**Comment by kaalabs** [comment]
Did the re-install. Still few errors but now at least there are boards in the output:

MacBook-van-Remco:~ remcokortekaas$ cuwire boards
bad config for: recipe.size.regex.data ^(?:.data|.bss|.noinit)\s+([0-9]+).*
bad config for: recipe.size.regex.eeprom ^(?:.eeprom)\s+([0-9]+).*
cuwire using runtime from /Applications/Arduino.app/Contents/Java
cuwire boards available:
Arduino AVR Boards (arduino:avr) 1.5.8
LilyPad Arduino USB (LilyPadUSB)
Arduino NG or older (atmegang, models: cpu:atmega168 [ATmega168], cpu:atmega8 [ATmega8])
Arduino BT (bt, models: cpu:atmega328 [ATmega328], cpu:atmega168 [ATmega168])
Arduino Duemilanove or Diecimila (diecimila, models: cpu:atmega328 [ATmega328], cpu:atmega168 [ATmega168])
Arduino Esplora (esplora)
Arduino Ethernet (ethernet)
Arduino Fio (fio)
Arduino Leonardo (leonardo)
LilyPad Arduino (lilypad, models: cpu:atmega328 [ATmega328], cpu:atmega168 [ATmega168])
Arduino Mega or Mega 2560 (mega, models: cpu:atmega2560 [ATmega2560 (Mega 2560)], cpu:atmega1280 [ATmega1280])
Arduino Mega ADK (megaADK)
Arduino Micro (micro)
Arduino Mini (mini, models: cpu:atmega328 [ATmega328], cpu:atmega168 [ATmega168])
Arduino Nano (nano, models: cpu:atmega328 [ATmega328], cpu:atmega168 [ATmega168])
Arduino Pro or Pro Mini (pro, models: cpu:16MHzatmega328 [ATmega328 (5V, 16 MHz)], cpu:8MHzatmega328 [ATmega328 (3.3V, 8 MHz)], cpu:16MHzatmega168 [ATmega168 (5V, 16 MHz)], cpu:8MHzatmega168 [ATmega168 (3.3V, 8 MHz)])
Arduino Robot Control (robotControl)
Arduino Robot Motor (robotMotor)
Arduino Uno (uno)
Arduino Yún (yun)
Arduino ARM (32-bits) Boards (arduino:sam) 1.5.8
Arduino Due (Native USB Port) (arduino_due_x)
Arduino Due (Programming Port) (arduino_due_x_dbg)

TypeError: Cannot read property 'version' of undefined
    at /usr/local/lib/node_modules/cuwire/cli.js:310:53
    at Array.forEach (native)
    at ArduinoCli.showBoards (/usr/local/lib/node_modules/cuwire/cli.js:308:33)
    at null.<anonymous> (/usr/local/lib/node_modules/cuwire/cli.js:207:20)
    at ArduinoCli.launchCommand (/usr/local/lib/node_modules/cuwire/cli.js:210:2)
    at null.<anonymous> (/usr/local/lib/node_modules/cuwire/cli.js:188:8)
    at emit (events.js:92:17)
    at null.<anonymous> (/usr/local/lib/node_modules/cuwire/data.js:132:8)
    at emit (events.js:117:20)
    at null._onTimeout (/usr/local/lib/node_modules/cuwire/data.js:171:11)

**Comment by apla** [comment]
pushed another commit to check error ownership

**Comment by kaalabs** [comment]
It now works fine! Thanks. Maybe i'll come back. Seeing other strange behavior but have to watch more closely first.

**Comment by zenakuten** [comment]
I'm also having the same issue.  

c:>cuwire boards
bad config for: recipe.size.regex.data ^(?:.data|.bss|.noinit)\s+([0-9]+).*
bad config for: recipe.size.regex.eeprom ^(?:.eeprom)\s+([0-9]+).*

I'm using node v0.12.0, arduino 1.58, and brackets 1.1 on Win 7 x64.  

I also get the same error if I run node cli.js boards.

**Comment by apla** [comment]
Just published new version, 0.5.8. If problem persists, please let me know.

**Comment by zenakuten** [comment]
The newer version works for me.  Thank you!
